---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mykube-deployment
  labels:
    app: mykube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mykube
  template:
    metadata:
      labels:
        app: mykube
    spec:
      serviceAccountName: mykube-serviceaccount
      containers:
        - name: mykube
          image: rezacomplete/mykube:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: mykube-service
spec:
  selector:
    app: mykube
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379  # Default Redis port
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379  # The port that the service will expose
      targetPort: 6379  # The port to which the service routes traffic
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mykube-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: mykube.local
      http:
        paths:
          - path: /shorten
            pathType: Prefix
            backend:
              service:
                name: mykube-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mykube-service
                port:
                  number: 80
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: mykube-serviceaccount
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: default
subjects:
  - kind: ServiceAccount
    name: mykube-serviceaccount
    namespace: default
roleRef:
  kind: Role
  name: pod-reader
---


